Remove inappropriate compara databases
Ensembl/ensembl-datacheck pull request #403
Opened 2021-09-06 11:23 UTC by JAlvarezJarreta

`SchemaPatchesApplied` DC is not applicable for the rapid release Compara databases (References and Homology annotation at the moment) as they follow a different schema.

2021-09-06 12:06 UTC, CristiGuijarro requested changes
Requires reindexing index.json file, but otherwise a necessary change for RR

2021-09-06 13:16 UTC, CristiGuijarro approved these changes

2021-09-07 11:35 UTC, james-monkeyshines reviewed
I'm not sure that this will work at handover - the 'compara' group will be run then, so will this fail at that point? Or is it only during pipeline execution that this will be a problem?
And if the schema is different, won't [CompareSchema](https://github.com/Ensembl/ensembl-datacheck/blob/release/105/lib/Bio/EnsEMBL/DataCheck/Checks/CompareSchema.pm) also fail?

Other things may break in less obvious ways, because the datachecks expect 'compara' schemas to all look the same; if the rapid dbs are significantly different, we might need to address that explicitly.

One option would be to create yet another GROUP, say "compara_rapid"; that has the benefit of working in the current infrastructure, but it's a bit annoying, and maybe somewhat bug-prone, to maintain. The handover process would have to be updated to use this group, but we're planning to make the datachecks that are executed dependent on the target server anyway (https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-7112).

The alternative is to create a new DB_TYPE, say "compara_rapid" - this perhaps better reflects that we are working with a different beast, and would provide the flexibility to run a subset of datachecks for rapid, and also allow for RR-specific checks. But, this requires a bit more engineering in the background, this won't work out of the box.

2021-09-07 12:14 UTC, CristiGuijarro commented
> I'm not sure that this will work at handover - the 'compara' group will be run then, so will this fail at that point? Or is it only during pipeline execution that this will be a problem?
> And if the schema is different, won't [CompareSchema](https://github.com/Ensembl/ensembl-datacheck/blob/release/105/lib/Bio/EnsEMBL/DataCheck/Checks/CompareSchema.pm) also fail?
> 
> Other things may break in less obvious ways, because the datachecks expect 'compara' schemas to all look the same; if the rapid dbs are significantly different, we might need to address that explicitly.
> 
> One option would be to create yet another GROUP, say "compara_rapid"; that has the benefit of working in the current infrastructure, but it's a bit annoying, and maybe somewhat bug-prone, to maintain. The handover process would have to be updated to use this group, but we're planning to make the datachecks that are executed dependent on the target server anyway (https://www.ebi.ac.uk/panda/jira/browse/ENSPROD-7112).
> 
> The alternative is to create a new DB_TYPE, say "compara_rapid" - this perhaps better reflects that we are working with a different beast, and would provide the flexibility to run a subset of datachecks for rapid, and also allow for RR-specific checks. But, this requires a bit more engineering in the background, this won't work out of the box.

As far as I am aware, there will be no "handover" of the per-species compara databases for rapid release. The necessary DCs are incorporated in the pipelines to be run (and these run just the `compara_homology_annotation` group for the blastocyst pipeline and `compara_references` for the reference database update pipeline. The new databases are deposited directly on the rapid release server, with no further checks once they have passed those mentioned.

2021-09-07 12:34 UTC, james-monkeyshines commented
> As far as I am aware, there will be no "handover" of the per-species compara databases for rapid release. The necessary DCs are incorporated in the pipelines to be run (and these run just the `compara_homology_annotation` group for the blastocyst pipeline and `compara_references` for the reference database update pipeline. The new databases are deposited directly on the rapid release server, with no further checks once they have passed those mentioned.

Yes, sorry, you're right - I got a bit muddled. However, if we're not running the 'compara' group, then is the 'compara_homology_annotation' one sufficient? There are datachecks that are in the former but not the latter that  (e.g. CompareSchema, MySQLStorageEngine, WhitespaceCritical) which seem equally applicable to standard and RR dbs, and could cause bugs if they fail.

Another thing that has just occurred to me is that the divergence in schema may pose difficulties for us when we increment the Ensembl version for RR - our process is to rename the db with the new version, and then apply schema patches (automated with a script). Can we expect this to work for RR dbs?

2021-09-07 13:43 UTC, CristiGuijarro commented
> > As far as I am aware, there will be no "handover" of the per-species compara databases for rapid release. The necessary DCs are incorporated in the pipelines to be run (and these run just the `compara_homology_annotation` group for the blastocyst pipeline and `compara_references` for the reference database update pipeline. The new databases are deposited directly on the rapid release server, with no further checks once they have passed those mentioned.
> 
> Yes, sorry, you're right - I got a bit muddled. However, if we're not running the 'compara' group, then is the 'compara_homology_annotation' one sufficient? There are datachecks that are in the former but not the latter that (e.g. CompareSchema, MySQLStorageEngine, WhitespaceCritical) which seem equally applicable to standard and RR dbs, and could cause bugs if they fail.
> 
> Another thing that has just occurred to me is that the divergence in schema may pose difficulties for us when we increment the Ensembl version for RR - our process is to rename the db with the new version, and then apply schema patches (automated with a script). Can we expect this to work for RR dbs?

We could include `CompareSchema` and `WhiteSpaceCritical` in `compara_homology_annotation`  - I see no issue there, I must have missed those when creating the new groups initially. Should @JAlvarezJarreta include those in this PR?

2021-09-07 14:24 UTC, JAlvarezJarreta commented
I agree with you @james-monkeyshines the new DB_TYPE may actually fit best with how we are proceeding with our rapid release development (for now). But I think due to the need of homology annotation to be out asap (and the additional development required), this can be discussed in a meeting if you want (so the next compara RR pipelines are adapted to this approach). I'm happy to add those DCs you both seem deemed for these new compara databases in thir PR.

2021-09-07 15:12 UTC, JAlvarezJarreta commented
@CristiGuijarro, I will add those two DCs to `compara_references` since they seem useful as well, what do you think? I have added `MySQLStorageEngine` only to `compara_homology_annotation` as I feel this DC should be only applied to release databases.

2021-09-08 08:48 UTC, james-monkeyshines commented
Hi @JAlvarezJarreta, @CristiGuijarro, thanks for your comments/feedback. The three datachecks I highlighted were intended to be examples, rather than an exhaustive list - I've had another look at the generic datachecks (I'm assuming the more compara-y ones are fine), and I think DatabaseCollation and SchemaVersion would also be useful to have.

2021-09-08 08:56 UTC, CristiGuijarro commented
> Hi @JAlvarezJarreta, @CristiGuijarro, thanks for your comments/feedback. The three datachecks I highlighted were intended to be examples, rather than an exhaustive list - I've had another look at the generic datachecks (I'm assuming the more compara-y ones are fine), and I think DatabaseCollation and SchemaVersion would also be useful to have.

Can definitely include `DatabaseCollation`, and we could include `SchemaVersion` for now too -  but this may require change in the future (for example with the decoupled schema, we have not yet come up with a schema versioning system for the RR compara db - and I believe the db name will still need to fit with the main release versioning).

2021-09-08 09:35 UTC, CristiGuijarro approved these changes
:+1:  I think that should do it for now :crossed_fingers:

2021-09-08 09:37 UTC, james-monkeyshines approved these changes

2021-09-08 09:40 UTC, james-monkeyshines commented
Just spotted that this is against the master branch - for RR we run against the latest release branch for datachecks, ie release/105.
Are these changed needed right away? If so, I'll merge into the release branch (which will be merged back into master in the next week or two in any case).

2021-09-08 09:48 UTC, JAlvarezJarreta commented
Oh apologies! Yes, @luca-drf  is running the homology annotation pipeline atm so I guess he needs these changes asap. Thank you again @james-monkeyshines!

2021-09-08 10:44 UTC, JAlvarezJarreta commented
I have created a new PR with the right branches (see PR#405).

2021-09-08 10:44 UTC, closed without merging