New DC for checking that value for strain.type meta key is from approved list
Ensembl/ensembl-datacheck pull request #471
Opened 2022-04-21 12:02 UTC by leannehaggerty

This is my first DC from scratch so I apologise for any mistakes, but the test will be on Genebuild when we handover databases for RR34, if any issues pop up we will fix them immediately.

**Description**
We found that the value for strain.type meta key had been set incorrectly as "reference" for a db on RR, this DC should check that the value for strain.type can only be from the approved list (we can update this list as needed).

2022-04-21 13:03 UTC, ens-ap5 approved these changes
The default list looks good to me, but I know nothing about data check syntax :)

2022-04-22 11:11 UTC, marcoooo requested changes
The DC doesn't seem to be registered in index.json file.  therefore this DC would never be run.

2022-04-28 12:34 UTC, leannehaggerty commented
Thanks @marcoooo, I think it's ok now

2022-04-28 13:49 UTC, marcoooo approved these changes

2022-04-28 13:49 UTC, merged