Datacheck - VariationAncestralAllele
Ensembl/ensembl-datacheck pull request #488
Opened 2022-07-14 15:03 UTC by Gurpreet-Ghattaoraya

This datacheck is intented to make sure that, for human DBs, that the ancestral allele pipeline has ran - the pipeline populates the ancestral allele information for COSMIC and ClinVar variant sources. So the check makes sure these columns have data.

2022-07-14 15:22 UTC, marcoooo requested changes
Can you please update the description to give me more context about this PR? 
Check that you tested it on a sample db etc..
Thanks!

2022-07-14 15:59 UTC, marcoooo commented
> Hi @marcoooo - I have updated the description and I have asked @dglemos to review on the code on the Variation team side of things. I have tested the code against a few DBs - I can provide a link to the Jira ticket which show what I have tested
> 
> This is my first contribution to the Datachecks so I am still learning. Please let me know if I have missed anything else out?

Thanks!  Quick question, is it expected to be run for current release 108? If so, the PR should be opened against `release/108` branch.

2022-07-14 16:08 UTC, Gurpreet-Ghattaoraya commented
> 

Yes, we do want to run it on 108. I'll edit the pull request to point towards 108 instead.

2022-07-14 16:42 UTC, marcoooo commented
> > 
> 
> Yes, we do want to run it on 108. I'll edit the pull request to point towards 108 instead.

I am afraid your PR now include unwanted/untested commit. You might have to redo the updates from a fresh branch issued from current `release/108`

2022-07-15 08:49 UTC, Gurpreet-Ghattaoraya commented
> > > 
> > 
> > 
> > Yes, we do want to run it on 108. I'll edit the pull request to point towards 108 instead.
> 
> I am afraid your PR now include unwanted/untested commit. You might have to redo the updates from a fresh branch issued from current `release/108`

Yes sorry, I had originally creted my branch from main - I'll try again but using release/108.

2022-07-15 14:24 UTC, marcoooo reviewed
one general remarks, if possible, it's best to avoid direct SQL in DC, best to use the related API, because the day the schema changes... we can forget to update related DC.

2022-07-15 14:47 UTC, Gurpreet-Ghattaoraya commented
> one general remarks, if possible, it's best to avoid direct SQL in DC, best to use the related API, because the day the schema changes... we can forget to update related DC.

Can I clarify please? By "direct SQL" does that mean my example line of code
`my $is_COSMIC = $self->dba->dbc->sql_helper->execute(-SQL => $sql_COSMIC_exists);`  ?

2022-07-15 17:05 UTC, merged